# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-21 01:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusStop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bus_route', models.CharField(max_length=50)),
                ('stop_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=20)),
                ('user_name', models.CharField(max_length=20)),
                ('air_pollution', models.CharField(max_length=20)),
                ('wake_up_time', models.CharField(max_length=50)),
                ('sleep_time', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='WeatherPosition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.CharField(max_length=50)),
                ('longitude', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='echobot.UserProfile')),
            ],
        ),
        migrations.AddField(
            model_name='reminder',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='echobot.UserProfile'),
        ),
        migrations.AddField(
            model_name='busstop',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='echobot.UserProfile'),
        ),
    ]
