# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-21 02:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('echobot', '0002_auto_20170321_0946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='air_pollution',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='sleep_time',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_name',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='wake_up_time',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
