# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-21 07:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('echobot', '0004_userprofile_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_id',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
