# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-21 11:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('echobot', '0005_auto_20170321_1555'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weatherposition',
            name='user',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='latitude',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='longitude',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.DeleteModel(
            name='WeatherPosition',
        ),
    ]
