# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-21 11:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('echobot', '0006_auto_20170321_1919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_id',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
