# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-22 04:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('echobot', '0007_auto_20170321_1932'),
    ]

    operations = [
        migrations.CreateModel(
            name='DayKeyWord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=150)),
            ],
        ),
    ]
